- name: Copy HTML file to Nginx server directory
  hosts: all
  become: yes
  tasks:
    - name: Ensure Nginx is installed on Amazon Linux
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx is installed on Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx on Amazon Linux
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx on Ubuntu
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Copy HTML file to the Nginx web directory on Amazon Linux
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Copy HTML file to the Nginx web directory on Ubuntu
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Ensure Nginx is restarted to apply changes on Amazon Linux
      service:
        name: nginx
        state: restarted
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx is restarted to apply changes on Ubuntu
      service:
        name: nginx
        state: restarted
      when: ansible_os_family == "Debian"
